# Generated by Django 5.0.1 on 2024-01-20 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='indefinite',
        ),
    ]
