# Generated by Django 5.0.1 on 2024-01-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_userprofile_monthly_budget_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="monthly_budget_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="0", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="0", max_digits=10, null=True
            ),
        ),
    ]
